{% set version = "1.0.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-matlab
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/matlab_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/matlab/matlab_{{ version }}.tar.gz
  sha256: 1988a2220703444a575f2bad4eb090a0da71478599eb53081dd7237b7ec216ea

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('matlab')"           # [not win]
    - "\"%R%\" -e \"library('matlab')\""  # [win]

about:
  home: http://cran.r-project.org/package=matlab
  license: Artistic-2.0
  summary: Emulate MATLAB code using R
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
