{% set version = "1.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-matlab
  version: {{ version|replace("-", "_") }}

source:
  fn: matlab_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/matlab_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/matlab/matlab_{{ version }}.tar.gz
  sha256: a23dec736c51ae1864c1a53caac556a2f98e8020138a3b121badb0f5b7984154

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('matlab')"           # [not win]
    - "\"%R%\" -e \"library('matlab')\""  # [win]

about:
  home: http://cran.r-project.org/package=matlab
  license: Artistic-2.0
  summary: Emulate MATLAB code using R
  license_family: OTHER

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0
extra:
  recipe-maintainers:
    - conda-forge/r
    - fabio-cumbo
