travis:
  secure:
    BINSTAR_TOKEN: Q7d4UdiOzr7aOXPoIWrhTrVDa75gushYEJoZ3O6v/htTJxYIH5Zg1uOIwsAQ0igrCvGGDtfh0m1+Tk0tR9yeOof/q1jHdVYrRqS7kkl5NnMn8K6Pzp63tTy+JFU0Lz6sWXqx4svEXjTYu/QJou4Awte3Q0fVMowyFCKtDEsoPPvvGGzEeFRW1Ne1oGM/wSFJOvZW6NHW0sjoZyg1iChQDRdN+YqgW8dMQihbjZye7GUgLHR0VldaOH6qdKMn69kodeHNG6KRB84VvQcB/syA/A0cSR1Gz2RAB/vqheKl5Rb4XgFi7ZaxZwY7nNsdJAB7rgga8lH+y8Qu5uqy5SOg7VRJ4/CWMeo34+wmEMumdDIRMBdQJe9GQZ+G1+p90CHLC0+oiwD2a8pOBAVcedg66DCa83m0UaNonTMYwiXd/Fx1jbpgVS7IoeHH84gLOI9DpOV7G49bw4rhYfuKN3lJpp4WzBu9vB4j0br+uky1ZAYDXomeckS02TrIi6iiCDFgl1xDG5uXpqYU5q2cij2RGVfeKpw1kB3hhSpbOHeZ8jDbjgnlUwFh5ZOQ1mpduM99SbUTWF4i/ktZVL/Lg+rjv092X/733PM1S4krrpmjZXnHImSczRyVcOlWohzYuc3FLm1DkW01szdb0xNshSI+b36gGcad9JHSoKhiUsYNz6U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
