travis:
  secure:
    BINSTAR_TOKEN: Vyz/i6u+PwKW836rINyLRmnS0Y+RJ7t2BvII5rbSkrfPNj11mETjG83+LWHOdHR2VaMXqXfJt47LV0AWXFhMa8wOwrJckwY63bR31xguImXHNsXbnvu4rKafbdxycwcAhkDIUI/xgopADkSguDkOFGzcDT4zaKaSNlaTrzfXCTzpzLcf1+I9j7FEHcVDI9yU5I2o5MsQXS8HrkANNP6Dt/1CDAVqnpHSBPmLKDSNJ2fD6GthZdar8pjidwRCrtiJ91hoLD8SgHYWigSYQzJrmMTGTDhKDGKOUBCG9Ji8X7fMr2eOdZaxMzo0SeUyH8GGPJ1DHxywx3s++U3M+dwcpYoRWJaG6jQJBHypCoywFzNYz3A/V/5FN3sJ0/OXxiYy2NR00PiV1beaX4V13TeEvOPkS+oqxM4kGfFvAXYUfI6wlQoNGoaNlNM9rgfdr4+lqlK2l6y4w4IpUZYuKLYHZyLiVXOd1pkDR+AH6j8YO1FfWgDcNPw2djyYjcUcnadaKXREIJMme0ZUoGzWXtCNIZxWK6MWIUXIk0DTQrXLlbb/lZhrMiIWDXXIYKb0hgMlT8VXuG77Yltk/5F0otNHu3XtElPfP3zT8Y/H56iH7wq5qd+bJwRPSjF5NSgiZQv2l+oY9VeezqIGvgON5ibL0q/QgZbwDjmJiilWF3KsZvk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
