travis:
  secure:
    BINSTAR_TOKEN: Zeba0KJ4jgPiZZgP+HhkSnfl9ztjim5xWSc+pI5O/Xe8a2TE1CsBk2Ak+CwVczfbSnFSpbxsZKsifk0MMrDDtGRUKQm2yQFk5D4NQ8RQn/qFjtezYbC4OIvyE1VlIZfaMaG7sMioR1aCb+R6XS8ydeS8V0PgKmELvuOaPfOobOvykz9CdJI31gQ1FHl4NA9fWht44qDRUqe81DozMuVCGun+dlXnoMDp//q4PXFDO9qnkeBzayjTU8T+RXSBtW2ojKwYPCNfEpmMO7+Sf8JKl3Yu5jiw7VTFqnfpdHD/uoi8Jv9P87l461ziAN2mLlpdLzSX4+BkBapAQiOC1qpNhclSahO7mfnIpu/KCTtfJjputd1C+MBQGOtSu/1xAnBCmeo2qsWap9+H5RHJOtD41l87OKhCYFKzeJCnEEwvnftDjea7dcQyQea1X5cJDhMGgrtOGNBdNqWbsBBZ81maJIn7wkjxkjbRgiCzdyj6LfQPDyTM1fv40vqRxAmwz2sqn9nICATc6kf6xCL9CuutADTEduHjFMl/uNIDvwKderzORb7zck7ZX+tVuL/r+zfGPgtgEFPql3Us3gf8XSeuxLHFfQfFlfcz0XUKXtxs1HMxwR+f1Mfq0ofXMjLOvCNzPkH00Ij0uJWgASfO59hjR0ttcmttwueO7MH8+rUjCPM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
